# Generated by Django 5.2.12 on 2026-03-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="name_hebrew",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
