# Generated by Django 5.2.12 on 2026-03-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_medicine_name_hebrew"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=50, unique=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
