# Generated by Django 5.2.12 on 2026-03-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_visitor"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissedRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_searched", models.CharField(max_length=200)),
                ("requester_phone", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "suggestion_given",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
