# Generated by Django 5.2.12 on 2026-03-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_missedrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
