# Generated by Django 5.2.12 on 2026-03-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_medicine_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="min_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="suitable_pregnant",
            field=models.BooleanField(default=False),
        ),
    ]
