# Generated by Django 5.2.12 on 2026-03-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_medicine_expiry_date_medicine_min_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=200)),
                ("requester_phone", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("was_available", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
